# *WARNING* Do not change this file as it may break your notebooks

import os
os.environ['HOME'] = '/home/0ef25bb7-293c-4b29-a634-b20f88fbae61'
os.environ['LC_CTYPE'] = 'en_US.utf-8'
os.environ['JAVA_HOME'] = '/usr/lib/jvm/default-java'
os.environ['TERM'] = 'xterm-256color'
os.environ['PYTHONSTARTUP'] = '/home/0ef25bb7-293c-4b29-a634-b20f88fbae61/.pythonstartup.py'
os.environ['PYTHONANYWHERE_DOMAIN'] = 'anacondaapps.cloud'
os.environ['PYTHONANYWHERE_SITE'] = 'nb.anaconda.com'
os.environ['ANACONDA_API_DOMAIN'] = 'anaconda.com'
os.environ['ANACONDA_API_URL'] = 'https://anaconda.com/api'
os.environ['ANACONDA_APP_URL'] = 'https://anaconda.com/app'
os.environ['ANACONDA_ASSISTANT_API_URL'] = 'https://anaconda.com/api/assistant'
os.environ['ANACONDA_ASSISTANT_ENVIRONMENT_TYPE'] = 'cloud-notebooks-prod'
os.environ['ANACONDA_AUTH_DOMAIN'] = 'auth.anaconda.com'
os.environ['ANACONDA_IAM_URL'] = 'https://anaconda.com/api/iam'
os.environ['ANACONDA_LEARNING_URL'] = 'https://learning.anaconda.com'
os.environ['ANACONDA_NOTEBOOKS_URL'] = 'https://nb.anaconda.com'
os.environ['ANACONDA_PROJECTS_DIR'] = 'anaconda_projects'
os.environ['http_proxy'] = 'http://proxy.server:3128'
os.environ['https_proxy'] = 'http://proxy.server:3128'
os.environ['no_proxy'] = 'localhost,127.0.0.1,localaddress,.localdomain.com,/var/run/docker.sock'
os.environ['API_TOKEN'] = '6e0d4ae612053a92a59f4eb81f5755c522e1b7a7'
